const DESIGNATIONS = {
  ADMIN: 'ADMIN',
  COUNSILOR: 'COUNSILOR',
  RECRUITER: 'RECRUITER',
  MANAGER: 'MANAGER',
  CRE: 'CRE',
  FIELD_EXECUTIVE: 'FIELD_EXECUTIVE',
};

const BOOKING_STATUSES = {
    PENDING: 'PENDING',
    PROCESSING: 'PROCESSING',
    CONFIRMED: 'CONFIRMED',
    CANCELLED: 'CANCELLED',
    COMPLETED: 'COMPLETED',
    
};
const STATUSES = {
    ACTIVE: 'ACTIVE',
    INACTIVE: 'INACTIVE',
    DELETED: 'DELETED',
    BLOCKED: 'BLOCKED',
    DEAD: 'DEAD',
    REGISTER: 'REGISTER',
    FOLLOW_UP: 'FOLLOW_UP',
    UNASSIGNED: 'UNASSIGNED',
    NEW:'NEW',
    CRE: 'CRE',
    INTRESTED: 'INTRESTED',
    CONVERTED: 'CONVERTED',
};

module.exports = {
  DESIGNATIONS,
  STATUSES,
  BOOKING_STATUSES
};
