const DESIGNATIONS = {
  COUNSILOR: 'COUNSILOR',
  RECRUITER: 'RECRUITER',
  MANAGER: 'MANAGER',
  FIELD_EXECUTIVE: 'FIELD_EXECUTIVE',
};

const STATUSES = {
    ACTIVE: 'ACTIVE',
    INACTIVE: 'INACTIVE',
    DELETED: 'DELETED',
    BLOCKED: 'BLOCKED',
    DEAD: 'DEAD',
    REGISTER: 'REGISTER',
    FOLLOW_UP: 'FOLLOW_UP',
    UNASSIGNED: 'UNASSIGNED',
};

module.exports = {
  DESIGNATIONS,
  STATUSES
};
