const DESIGNATIONS = {
  ADMIN: 'ADMIN',
  COUNSILOR: 'COUNSILOR',
  RECRUITER: 'RECRUITER',
  MANAGER: 'MANAGER',
  CRE: 'CRE',
  FIELD_EXECUTIVE: 'FIELD_EXECUTIVE',
};

const BOOKING_STATUSES = {
  PENDING: 'PENDING',
  PROCESSING: 'PROCESSING',
  CONFIRMED: 'CONFIRMED',
  CANCELLED: 'CANCELLED',
  COMPLETED: 'COMPLETED',

};

const EVENT_STATUSES = {
  SCHEDULED: 'SCHEDULED',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
  POSTPONED: 'POSTPONED',
};

const EVENT_TYPES = {
  MEETING: 'MEETING',
  CALL: 'CALL',
  SITE_VISIT: 'SITE_VISIT',
  FOLLOW_UP: 'FOLLOW_UP',
  PRESENTATION: 'PRESENTATION',
  OTHER: 'OTHER',
};
const STATUSES = {
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE',
  DELETED: 'DELETED',
  DISCONTINUED: 'DISCONTINUED',
  BLOCKED: 'BLOCKED',
  DEAD: 'DEAD',
  UPCOMING: 'UPCOMING',
  REGISTER: 'REGISTER',
  FOLLOW_UP: 'FOLLOW_UP',
  UNASSIGNED: 'UNASSIGNED',
  NEW: 'NEW',
  CRE: 'CRE',
  INTRESTED: 'INTRESTED',
  CONVERTED: 'CONVERTED',
};

module.exports = {
  DESIGNATIONS,
  STATUSES,
  BOOKING_STATUSES,
  EVENT_STATUSES,
  EVENT_TYPES
};
